-- Clínica Vida+ | schema.sql
create table if not exists especialidades (
  id bigint generated by default as identity primary key,
  nome varchar(80) not null unique,
  descricao text,
  ativo boolean not null default true
);

create table if not exists profissionais (
  id bigint generated by default as identity primary key,
  nome varchar(120) not null,
  registro varchar(30) not null unique,
  especialidade_id bigint not null references especialidades(id),
  ativo boolean not null default true,
  criado_em timestamp not null default now()
);

create table if not exists pacientes (
  id bigint generated by default as identity primary key,
  nome varchar(120) not null,
  email varchar(150) unique,
  telefone varchar(25),
  data_nascimento date not null,
  ativo boolean not null default true,
  criado_em timestamp not null default now()
);

create table if not exists consultas (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references pacientes(id),
  profissional_id bigint not null references profissionais(id),
  data_hora timestamp not null,
  modalidade varchar(20) not null check (modalidade in ('Presencial','Online')),
  status varchar(20) not null check (status in ('Agendada','Concluída','Cancelada','Pendente')),
  valor numeric(10,2) not null check (valor >= 0),
  observacoes text
);

create table if not exists pagamentos (
  id bigint generated by default as identity primary key,
  consulta_id bigint not null unique references consultas(id),
  valor numeric(10,2) not null check (valor >= 0),
  vencimento date not null,
  status varchar(20) not null check (status in ('Pago','Pendente','Cancelado')),
  pago_em timestamp
);

create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  nome varchar(120) not null,
  email varchar(150) not null unique,
  perfil varchar(30) not null check (perfil in ('Administrador','Recepção','Gestor')),
  ativo boolean not null default true
);

create index if not exists idx_consultas_data on consultas(data_hora);
create index if not exists idx_consultas_paciente on consultas(paciente_id);
create index if not exists idx_consultas_profissional on consultas(profissional_id);
